# Generated by Django 4.0.4 on 2022-05-27 17:32

import attendance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_photo', models.ImageField(upload_to=attendance.models.user_directory_path)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
