# Generated by Django 4.0.4 on 2022-05-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_photo',
            new_name='imageBase64',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='post',
            new_name='stationId',
        ),
    ]
